name: flog3
publish_to: none
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  path: ^1.8.0
  dart_ilogger:
    path: ../flutter_packages/dart_ilogger
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  characters: ^1.2.1
  uuid: ^3.0.6
  meta: ^1.8.0
  json_annotation: ^4.6.0
  collection: ^1.16.0
  dart_console: ^1.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
